### PR TITLE
ADD RDS based PDS Nucleus product completion checker lambda functions

### PR DESCRIPTION
**Pull request by ramesh-maddegoda**
## 🗒️ Summary
RDS based PDS Nucleus product completion checker lambda functions

In this RDS based approach, we use 2 lambda functions.
1. pds-nucleus-product-writer.py - To write files to EFS and store file names to RDS tables when we receive files
2. pds-nucleus-product-completion-checker.py - To check the completion status of products and notify completed products to an SQS queue (will be triggered on a schedule- E.g.: Every 3 minutes)

## ♻️ Related Issues
https://github.com/NASA-PDS/nucleus/issues/65

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
This looks like it'll work.

However, none of the Python sources follow the PEP8 standards that the [template-repo-python](https://github.com/NASA-PDS/template-repo-python) recommends and enforces with the `.pre-commit-hooks.yaml`.

There is a `.pre-commit-hooks.yaml` file in this repository, but it doesn't list `flake8` or `black`.

Is it okay to have lambda functions diverge from the rest of our Python sources? @ramesh-maddegoda @sjoshi-jpl @jordanpadams? I don't mind myself but I want to double-check with the other reviewers.

**Review by jordanpadams — CHANGES_REQUESTED** [review]
per comments from @nutjob4life , let's add these back if possible:

> There is a .pre-commit-hooks.yaml file in this repository, but it doesn't list `flake8` or `black`.

**Review by tloubrieu-jpl — APPROVED** [review]
Thanks @ramesh-maddegoda

**Comment by ramesh-maddegoda** [comment]
> per comments from @nutjob4life , let's add these back if possible:
> 
> > There is a .pre-commit-hooks.yaml file in this repository, but it doesn't list `flake8` or `black`.

@jordanpadams , I made the requested changes.

**Pull request merged**
